"""
Copyright 2025 binary butterfly GmbH
Use of this source code is governed by an MIT-style license that can be found in the LICENSE.txt.
"""

from unittest.mock import ANY

PARKING_SITE_LIST_RESPONSE = {
    'items': [
        {
            'source_id': 1,
            'original_uid': 'demo-parking-site-1',
            'name': 'Demo Parking Site 1',
            'operator_name': 'Demo Operator',
            'address': 'Demo Address, Demo City',
            'description': 'Demo Description',
            'type': 'CAR_PARK',
            'purpose': 'CAR',
            'has_fee': False,
            'has_realtime_data': False,
            'lat': '50.1000000',
            'lon': '10.1000000',
            'capacity': 100,
            'opening_hours': 'Mo-Su 08:00-18:00',
            'id': 1,
            'created_at': ANY,
            'modified_at': ANY,
        },
        {
            'source_id': 1,
            'original_uid': 'demo-parking-site-2',
            'name': 'Demo Parking Site 2',
            'operator_name': 'Demo Operator',
            'address': 'Demo Address, Demo City',
            'description': 'Demo Description',
            'type': 'CAR_PARK',
            'purpose': 'CAR',
            'has_fee': False,
            'has_realtime_data': False,
            'lat': '50.2000000',
            'lon': '10.2000000',
            'capacity': 100,
            'opening_hours': 'Mo-Su 08:00-18:00',
            'id': 2,
            'created_at': ANY,
            'modified_at': ANY,
        },
        {
            'source_id': 1,
            'original_uid': 'demo-parking-site-3',
            'name': 'Demo Parking Site 3',
            'operator_name': 'Demo Operator',
            'address': 'Demo Address, Demo City',
            'description': 'Demo Description',
            'type': 'CAR_PARK',
            'purpose': 'CAR',
            'has_fee': False,
            'has_realtime_data': False,
            'lat': '50.3000000',
            'lon': '10.3000000',
            'capacity': 100,
            'opening_hours': 'Mo-Su 08:00-18:00',
            'id': 3,
            'created_at': ANY,
            'modified_at': ANY,
        },
        {
            'source_id': 2,
            'original_uid': 'demo-parking-site-4',
            'name': 'Demo Parking Site 4',
            'operator_name': 'Demo Operator',
            'address': 'Demo Address, Demo City',
            'description': 'Demo Description',
            'type': 'CAR_PARK',
            'purpose': 'CAR',
            'has_fee': False,
            'has_realtime_data': False,
            'lat': '50.4000000',
            'lon': '10.4000000',
            'capacity': 100,
            'opening_hours': 'Mo-Su 08:00-18:00',
            'id': 4,
            'created_at': ANY,
            'modified_at': ANY,
        },
        {
            'source_id': 2,
            'original_uid': 'demo-parking-site-5',
            'name': 'Demo Parking Site 5',
            'operator_name': 'Demo Operator',
            'address': 'Demo Address, Demo City',
            'description': 'Demo Description',
            'type': 'CAR_PARK',
            'purpose': 'CAR',
            'has_fee': False,
            'has_realtime_data': False,
            'lat': '50.5000000',
            'lon': '10.5000000',
            'capacity': 100,
            'opening_hours': 'Mo-Su 08:00-18:00',
            'id': 5,
            'created_at': ANY,
            'modified_at': ANY,
        },
        {
            'source_id': 3,
            'original_uid': 'demo-parking-site-6',
            'name': 'Demo Parking Site 6',
            'operator_name': 'Demo Operator',
            'address': 'Demo Address, Demo City',
            'description': 'Demo Description',
            'type': 'CAR_PARK',
            'purpose': 'CAR',
            'has_fee': False,
            'has_realtime_data': False,
            'lat': '50.6000000',
            'lon': '10.6000000',
            'capacity': 100,
            'opening_hours': 'Mo-Su 08:00-18:00',
            'id': 6,
            'created_at': ANY,
            'modified_at': ANY,
        },
    ],
    'total_count': 6,
}

PARKING_SITE_ITEM_RESPONSE = {
    'source_id': 1,
    'original_uid': 'demo-parking-site-1',
    'name': 'Demo Parking Site 1',
    'operator_name': 'Demo Operator',
    'address': 'Demo Address, Demo City',
    'description': 'Demo Description',
    'type': 'CAR_PARK',
    'purpose': 'CAR',
    'has_fee': False,
    'has_realtime_data': False,
    'lat': '50.1000000',
    'lon': '10.1000000',
    'capacity': 100,
    'opening_hours': 'Mo-Su 08:00-18:00',
    'id': 1,
    'created_at': ANY,
    'modified_at': ANY,
}
