"""
Copyright 2025 binary butterfly GmbH
Use of this source code is governed by an MIT-style license that can be found in the LICENSE.txt.
"""

from unittest.mock import ANY

PARKING_SPOT_LIST_RESPONSE = {
    'items': [
        {
            'source_id': 1,
            'original_uid': 'demo-parking-spot-1',
            'lat': '50.1000000',
            'lon': '10.1000000',
            'realtime_status': 'AVAILABLE',
            'static_data_updated_at': ANY,
            'realtime_data_updated_at': ANY,
            'has_realtime_data': True,
            'purpose': 'CAR',
            'name': 'Test',
            'geojson': {
                'coordinates': [[[50.1, 10.1], [50.2, 10.1], [50.2, 10.2], [50.1, 10.2], [50.1, 10.1]]],
                'type': 'Polygon',
            },
            'id': 1,
            'created_at': ANY,
            'modified_at': ANY,
        },
        {
            'source_id': 1,
            'original_uid': 'demo-parking-spot-2',
            'lat': '50.2000000',
            'lon': '10.2000000',
            'realtime_status': 'AVAILABLE',
            'static_data_updated_at': ANY,
            'realtime_data_updated_at': ANY,
            'has_realtime_data': True,
            'purpose': 'CAR',
            'name': 'Test',
            'geojson': {
                'coordinates': [[[50.2, 10.2], [50.3, 10.2], [50.3, 10.3], [50.2, 10.3], [50.2, 10.2]]],
                'type': 'Polygon',
            },
            'id': 2,
            'created_at': ANY,
            'modified_at': ANY,
        },
        {
            'source_id': 1,
            'original_uid': 'demo-parking-spot-3',
            'lat': '50.3000000',
            'lon': '10.3000000',
            'realtime_status': 'AVAILABLE',
            'static_data_updated_at': ANY,
            'realtime_data_updated_at': ANY,
            'has_realtime_data': True,
            'purpose': 'CAR',
            'name': 'Test',
            'geojson': {
                'coordinates': [[[50.3, 10.3], [50.4, 10.3], [50.4, 10.4], [50.3, 10.4], [50.3, 10.3]]],
                'type': 'Polygon',
            },
            'id': 3,
            'created_at': ANY,
            'modified_at': ANY,
        },
        {
            'source_id': 2,
            'original_uid': 'demo-parking-spot-4',
            'lat': '50.4000000',
            'lon': '10.4000000',
            'realtime_status': 'AVAILABLE',
            'static_data_updated_at': ANY,
            'realtime_data_updated_at': ANY,
            'has_realtime_data': True,
            'purpose': 'CAR',
            'name': 'Test',
            'geojson': {
                'coordinates': [[[50.4, 10.4], [50.5, 10.4], [50.5, 10.5], [50.4, 10.5], [50.4, 10.4]]],
                'type': 'Polygon',
            },
            'id': 4,
            'created_at': ANY,
            'modified_at': ANY,
        },
        {
            'source_id': 2,
            'original_uid': 'demo-parking-spot-5',
            'lat': '50.5000000',
            'lon': '10.5000000',
            'realtime_status': 'AVAILABLE',
            'static_data_updated_at': ANY,
            'realtime_data_updated_at': ANY,
            'has_realtime_data': True,
            'purpose': 'CAR',
            'name': 'Test',
            'geojson': {
                'coordinates': [[[50.5, 10.5], [50.6, 10.5], [50.6, 10.6], [50.5, 10.6], [50.5, 10.5]]],
                'type': 'Polygon',
            },
            'id': 5,
            'created_at': ANY,
            'modified_at': ANY,
        },
        {
            'source_id': 3,
            'original_uid': 'demo-parking-spot-6',
            'lat': '50.6000000',
            'lon': '10.6000000',
            'realtime_status': 'AVAILABLE',
            'static_data_updated_at': ANY,
            'realtime_data_updated_at': ANY,
            'has_realtime_data': True,
            'purpose': 'CAR',
            'name': 'Test',
            'geojson': {
                'coordinates': [[[50.6, 10.6], [50.7, 10.6], [50.7, 10.7], [50.6, 10.7], [50.6, 10.6]]],
                'type': 'Polygon',
            },
            'id': 6,
            'created_at': ANY,
            'modified_at': ANY,
        },
    ],
    'total_count': 6,
}


PARKING_SPOT_ITEM_RESPONSE = {
    'source_id': 1,
    'original_uid': 'demo-parking-spot-1',
    'lat': '50.1000000',
    'lon': '10.1000000',
    'realtime_status': 'AVAILABLE',
    'static_data_updated_at': ANY,
    'realtime_data_updated_at': ANY,
    'has_realtime_data': True,
    'purpose': 'CAR',
    'name': 'Test',
    'geojson': {
        'coordinates': [[[50.1, 10.1], [50.2, 10.1], [50.2, 10.2], [50.1, 10.2], [50.1, 10.1]]],
        'type': 'Polygon',
    },
    'id': 1,
    'created_at': ANY,
    'modified_at': ANY,
}
