"""
Copyright 2025 binary butterfly GmbH
Use of this source code is governed by an MIT-style license that can be found in the LICENSE.txt.
"""

from flask_openapi.decorator import Schema
from flask_openapi.schema import (
    DateTimeField,
    IntegerField,
    JsonSchema,
    StringField,
)

parking_site_group_schema = JsonSchema(
    title='ParkingSiteHistory',
    required=False,
    properties={
        'id': IntegerField(description='Internal ID, generated by ParkAPI Service.'),
        'created_at': DateTimeField(description='Creation date in ParkAPI Service database, cannot be set by clients.'),
        'modified_at': DateTimeField(
            description='Last modified value in ParkAPI Service database, cannot be set by clients.',
        ),
        'original_uid': StringField(maxLength=256, description='Unique Identifier in original system.'),
    },
)


parking_site_group_example = {}


parking_site_group_component = Schema(
    'ParkingSiteGroup',
    schema=parking_site_group_schema,
    example=parking_site_group_example,
)
