"""
Copyright 2025 binary butterfly GmbH
Use of this source code is governed by an MIT-style license that can be found in the LICENSE.txt.
"""

from flask_openapi.decorator import Schema
from flask_openapi.schema import (
    AnyOfField,
    ArrayField,
    BooleanField,
    DateTimeField,
    EnumField,
    IntegerField,
    JsonSchema,
    NumericField,
    ObjectField,
    Reference,
    StringField,
)
from parkapi_sources.models.enums import ExternalIdentifierType, ParkingSpotType, PurposeType

from webapp.models.parking_spot import ParkingSpotStatus

parking_spot_schema = JsonSchema(
    title='ParkingSpot',
    properties={
        'id': IntegerField(description='Internal ID, generated by ParkAPI Service.'),
        'created_at': DateTimeField(description='Creation date in ParkAPI Service database, cannot be set by clients.'),
        'modified_at': DateTimeField(
            description='Last modified value in ParkAPI Service database, cannot be set by clients.',
        ),
        'source_id': IntegerField(minimum=1, description='Source ID, generated by ParkAPI Service.'),
        'parking_site_id': IntegerField(
            minimum=1,
            required=False,
            description='ParkingSite ID, generated by ParkAPI Service.',
        ),
        'original_uid': StringField(maxLength=256, description='Unique Identifier in original system.'),
        'type': EnumField(enum=ParkingSpotType, required=False),
        'description': StringField(required=False, maxLength=4096),
        'address': StringField(required=False, maxLength=256),
        'lat': NumericField(),
        'lon': NumericField(),
        'official_region_code': StringField(
            maxLength=36,
            required=False,
            nullable=True,
            description='German Regionalschlüssel / Gemeindeschlüssel, derived from the coordinates.',
        ),
        'name': StringField(maxLength=256, required=False),
        'purpose': EnumField(enum=PurposeType),
        'geojson': ObjectField(
            required=False,
            description='GeoJSON geometry. Additional attribute is `coordinates` containing coordinates depending '
            'on `type`.',
            properties={
                'type': AnyOfField(allowed_values=['Polygon', 'MultiPolygon', 'LineString', 'MultiLineString']),
            },
            additionalProperties=True,
        ),
        'restrictions': ArrayField(
            items=Reference(obj='ParkingSpotRestriction'),
            required=False,
            description='Restrictions which apply. If there are multiple options, they should be understood with an '
            'logical or.',
        ),
        'has_realtime_data': BooleanField(
            description='Whether the parking spot has usable realtime data. False if the parking spot is static, or if it is dynamic, but its '
            'realtime data is outdated (older than 30 minutes for pull sources, older than 24 hours for push '
            'sources). Realtime fields are provided anyway, so realtime_data_updated_at shows their age. Can be '
            'disabled with calculate_has_realtime_data=false.',
        ),
        'realtime_status': EnumField(enum=ParkingSpotStatus, required=False),
        'static_data_updated_at': DateTimeField(
            required=False,
            description='Last time static fields were updated. Can be set by the client.',
        ),
        'realtime_data_updated_at': DateTimeField(
            required=False,
            description='Last time realtime fields were updated. Can be set by the client.',
        ),
        'external_identifiers': ArrayField(
            items=ObjectField(
                properties={
                    'type': EnumField(enum=ExternalIdentifierType),
                    'value': StringField(maxLength=256),
                },
            ),
            required=False,
        ),
        'tags': ArrayField(
            items=StringField(maxLength=256),
            required=False,
            description='Free-form tags provided by the data source. Omitted if there are no tags.',
        ),
    },
)


parking_spot_example = {
    'id': 1,
    'created_at': '2025-03-21T17:53:29Z',
    'modified_at': '2025-03-21T17:53:29Z',
    'source_id': 1,
    'parking_site_id': 1,
    'original_uid': 'demo-parking-spot-1',
    'name': 'Demo Parking Spot 1',
    'type': 'ON_STREET',
    'purpose': 'CAR',
    'lat': 50.1,
    'lon': 10.1,
    'has_realtime_data': True,
    'realtime_status': 'AVAILABLE',
    'static_data_updated_at': '2025-03-21T17:53:29Z',
    'realtime_data_updated_at': '2025-03-21T18:00:00Z',
    'tags': ['demo-tag'],
}


parking_spot_component = Schema('ParkingSpot', parking_spot_schema, parking_spot_example)
