"""
Copyright 2025 binary butterfly GmbH
Use of this source code is governed by an MIT-style license that can be found in the LICENSE.txt.
"""

from flask_openapi.decorator import Schema
from flask_openapi.schema import (
    AnyOfField,
    ArrayField,
    BooleanField,
    DateTimeField,
    DecimalField,
    EnumField,
    IntegerField,
    JsonSchema,
    NumericField,
    ObjectField,
    Reference,
    StringField,
)

from webapp.models.parking_spot import ParkingSpotStatus

parking_spot_schema = JsonSchema(
    title='ParkingSpot',
    properties={
        'source_id': IntegerField(minimum=1, description='Source ID, generated by ParkAPI Service.'),
        'parking_site_id': IntegerField(
            minimum=1,
            required=False,
            description='ParkingSite ID, generated by ParkAPI Service.',
        ),
        'original_uid': StringField(maxLength=256, description='Unique Identifier in original system.'),
        'lat': DecimalField(precision=10, scale=7),
        'lon': DecimalField(precision=10, scale=7),
        'name': StringField(required=False),
        'purpose': EnumField(enum=ParkingSpotStatus),
        'geojson': ObjectField(
            required=False,
            description='ParkingSite GeoJSON geometry',
            properties={
                'type': AnyOfField(allowed_values=['Polygon']),
                'geometry': ArrayField(
                    items=ArrayField(
                        items=ArrayField(
                            items=NumericField(),
                            minItems=2,
                            maxItems=2,
                        ),
                    ),
                    minItems=1,
                    maxItems=1,
                ),
            },
        ),
        'restricted_to': ArrayField(
            items=Reference(obj='ParkingRestriction'),
            required=False,
            description='Restrictions which apply. If there are multiple options, they should be understood with an '
            'logical or.',
        ),
        'has_realtime_data': BooleanField(
            description='Whether the parking spot has realtime data or not.',
        ),
        'realtime_status': EnumField(enum=ParkingSpotStatus, required=False),
        'static_data_updated_at': DateTimeField(
            required=False,
            description='Last time static fields were updated. Can be set by the client.',
        ),
        'realtime_data_updated_at': DateTimeField(
            required=False,
            description='Last time realtime fields were updated. Can be set by the client.',
        ),
    },
)

parking_spot_example = {}

parking_spot_component = Schema('ParkingSpot', parking_spot_schema, parking_spot_example)
