"""split source status

Revision ID: a951c44669b8
Revises: 687daced5384
Create Date: 2023-12-09 09:12:50.644071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a951c44669b8'
down_revision = '687daced5384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('static_status', sa.Enum('DISABLED', 'ACTIVE', 'FAILED', 'PROVISIONED', name='sourcestatus'), server_default='PROVISIONED', nullable=False))
        batch_op.add_column(sa.Column('realtime_status', sa.Enum('DISABLED', 'ACTIVE', 'FAILED', 'PROVISIONED', name='sourcestatus'), server_default='PROVISIONED', nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('DISABLED', 'ACTIVE', 'FAILED', 'PROVISIONED', name='sourcestatus'), server_default='PROVISIONED', nullable=False))
        batch_op.drop_column('realtime_status')
        batch_op.drop_column('static_status')
    # ### end Alembic commands ###
