"""add indices

Revision ID: c4f85305ddee
Revises: 6be2c2aa3637
Create Date: 2024-04-07 08:30:20.373675

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c4f85305ddee'
down_revision = '6be2c2aa3637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_site_purpose'), ['purpose'], unique=False)

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_uid'), ['uid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_uid'))

    with op.batch_alter_table('parking_site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_site_purpose'))
    # ### end Alembic commands ###
