"""allow realtime opening status null

Revision ID: 4f09ed999210
Revises: 95992608c5d1
Create Date: 2024-11-20 09:06:51.525217

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f09ed999210'
down_revision = '95992608c5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_site', schema=None) as batch_op:
        batch_op.alter_column(
            'realtime_opening_status',
            existing_type=postgresql.ENUM('OPEN', 'CLOSED', 'UNKNOWN', name='openingstatus'),
            nullable=True,
        )

    with op.batch_alter_table('parking_site_history', schema=None) as batch_op:
        batch_op.alter_column(
            'realtime_opening_status',
            existing_type=postgresql.ENUM('OPEN', 'CLOSED', 'UNKNOWN', name='history_openingstatus'),
            type_=sa.Enum('OPEN', 'CLOSED', 'UNKNOWN', name='history_openingstatus'),
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_site_history', schema=None) as batch_op:
        batch_op.alter_column(
            'realtime_opening_status',
            existing_type=sa.Enum('OPEN', 'CLOSED', 'UNKNOWN', name='history_openingstatus'),
            type_=postgresql.ENUM('OPEN', 'CLOSED', 'UNKNOWN', name='history_openingstatus'),
            nullable=False,
        )

    with op.batch_alter_table('parking_site', schema=None) as batch_op:
        batch_op.alter_column(
            'realtime_opening_status',
            existing_type=postgresql.ENUM('OPEN', 'CLOSED', 'UNKNOWN', name='openingstatus'),
            nullable=False,
        )

    # ### end Alembic commands ###
