"""more fields, biking support

Revision ID: 6be2c2aa3637
Revises: ccd3da2086d3
Create Date: 2024-03-12 18:26:42.617665

"""
import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6be2c2aa3637'
down_revision = 'ccd3da2086d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_identifier',
    sa.Column('parking_site_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Enum('OSM', 'DHID', name='externalidentifiertype'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parking_site_id'], ['parking_site.id'], name=op.f('fk_external_identifier_parking_site_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_identifier')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('external_identifier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_identifier_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_identifier_modified_at'), ['modified_at'], unique=False)

    with op.batch_alter_table('parking_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.Enum('CAR', 'BIKE', 'ITEM', name='purposetype'), nullable=False))
        batch_op.add_column(sa.Column('is_covered', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('supervision_type', sa.Enum('YES', 'NO', 'VIDEO', 'ATTENDED', name='supervisiontype'), nullable=True))
        batch_op.add_column(sa.Column('related_location', sa.String(length=256), nullable=True))
        batch_op.drop_index('ix_geometry_index', mysql_prefix='SPATIAL')
        batch_op.drop_column('is_supervised')
        batch_op.alter_column(
            'type',
            existing_type=mysql.ENUM('ON_STREET', 'OFF_STREET_PARKING_GROUND', 'UNDERGROUND', 'CAR_PARK', 'OTHER'),
            type_=sa.Enum('ON_STREET', 'OFF_STREET_PARKING_GROUND', 'UNDERGROUND', 'CAR_PARK', 'WALL_LOOPS', 'STANDS', 'LOCKERS', 'SHED', 'TWO_TIER', 'BUILDING', 'OTHER', name='parkingsitetype'),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_supervised', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.create_index('ix_geometry_index', ['geometry'], unique=False, mysql_prefix='SPATIAL')
        batch_op.drop_column('related_location')
        batch_op.drop_column('supervision_type')
        batch_op.drop_column('is_covered')
        batch_op.drop_column('purpose')
        batch_op.alter_column(
            'type',
            existing_type=sa.Enum('ON_STREET', 'OFF_STREET_PARKING_GROUND', 'UNDERGROUND', 'CAR_PARK', 'WALL_LOOPS', 'STANDS', 'LOCKERS', 'SHED', 'TWO_TIER', 'BUILDING', 'OTHER', name='parkingsitetype'),
            type_=mysql.ENUM('ON_STREET', 'OFF_STREET_PARKING_GROUND', 'UNDERGROUND', 'CAR_PARK', 'OTHER'),
            existing_nullable=True,
        )

    with op.batch_alter_table('external_identifier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_identifier_modified_at'))
        batch_op.drop_index(batch_op.f('ix_external_identifier_created_at'))

    op.drop_table('external_identifier')
    # ### end Alembic commands ###
