"""longer fee description

Revision ID: 2dd84bdad484
Revises: ccd3da2086d3
Create Date: 2024-03-18 11:59:44.895124

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2dd84bdad484'
down_revision = 'ccd3da2086d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_site', schema=None) as batch_op:
        batch_op.alter_column('fee_description', existing_type=sa.VARCHAR(length=256), type_=sa.String(length=4096), existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_site', schema=None) as batch_op:
        batch_op.alter_column('fee_description', existing_type=sa.String(length=4096), type_=sa.VARCHAR(length=256), existing_nullable=True)

    # ### end Alembic commands ###
