"""restriction capacities

Revision ID: b88bc9bb7b4d
Revises: 46b6f06f010d
Create Date: 2025-10-20 17:47:21.532609

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b88bc9bb7b4d'
down_revision = '46b6f06f010d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_restriction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('realtime_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('realtime_free_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_restriction', schema=None) as batch_op:
        batch_op.drop_column('realtime_free_capacity')
        batch_op.drop_column('realtime_capacity')
        batch_op.drop_column('capacity')
    # ### end Alembic commands ###
