"""more parking spot properties

Revision ID: db3ef5b7669d
Revises: 82368571c72c
Create Date: 2025-05-18 11:45:14.937764

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'db3ef5b7669d'
down_revision = '82368571c72c'
branch_labels = None
depends_on = None


parking_spot_enum_fields = ['ON_STREET', 'OFF_STREET_PARKING_GROUND', 'UNDERGROUND', 'CAR_PARK', 'LOCKERS', 'LOCKBOX']


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(*parking_spot_enum_fields, name='parkingspottype').create(op.get_bind())
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('type', sa.Enum(*parking_spot_enum_fields, name='parkingspottype'), nullable=True)
        )
        batch_op.add_column(sa.Column('address', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('address')
        batch_op.drop_column('type')
    sa.Enum(*parking_spot_enum_fields, name='parkingspottype').drop(op.get_bind())
    # ### end Alembic commands ###
