"""add type index

Revision ID: 46b6f06f010d
Revises: 314b11ae0e1c
Create Date: 2025-08-11 18:38:44.005427

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = '46b6f06f010d'
down_revision = '314b11ae0e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_site_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_site_type'))
    # ### end Alembic commands ###
