"""add parking spot attributes

Revision ID: 82368571c72c
Revises: 8d2bcc119ee8
Create Date: 2025-05-08 18:26:35.308900

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '82368571c72c'
down_revision = '8d2bcc119ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('static_parking_spot_error_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('realtime_parking_spot_error_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('realtime_parking_spot_error_count')
        batch_op.drop_column('static_parking_spot_error_count')
    # ### end Alembic commands ###
