"""
Copyright 2025 binary butterfly GmbH
Use of this source code is governed by an MIT-style license that can be found in the LICENSE.txt.
"""

from flask_openapi.decorator import Schema
from flask_openapi.schema import (
    EnumField,
    IntegerField,
    JsonSchema,
    StringField,
)

from webapp.models.parking_restriction import ParkingAudience

base_properties = {
    'type': EnumField(
        enum=ParkingAudience,
        required=False,
        description='If type is not set, all audiences are restricted.',
    ),
    'hours': StringField(required=False, maxLength=512, description='Opening times in OSM format'),
    'max_stay': StringField(
        required=False,
        maxLength=256,
        description='Maximum stay period, based on ISO 8601 duration format.',
    ),
}

parking_spot_restriction_schema = JsonSchema(
    title='ParkingSpotRestriction',
    properties={
        'parking_spot_id': IntegerField(
            minimum=1,
            required=False,
            description='ParkingSpot ID, generated by ParkAPI Service.',
        ),
        **base_properties,
    },
)

parking_spot_restriction_example = {
    'parking_spot_id': 1,
    'type': 'WOMEN',
}


parking_spot_restriction_component = Schema(
    'ParkingSpotRestriction',
    parking_spot_restriction_schema,
    parking_spot_restriction_example,
)


parking_site_restriction_schema = JsonSchema(
    title='ParkingSiteRestriction',
    properties={
        'parking_spot_id': IntegerField(
            minimum=1,
            required=False,
            description='ParkingSpot ID, generated by ParkAPI Service.',
        ),
        'capacity': IntegerField(minimum=0, required=False),
        'realtime_capacity': IntegerField(minimum=0, required=False),
        'realtime_free_capacity': IntegerField(minimum=0, required=False),
        **base_properties,
    },
)

parking_site_restriction_example = {
    'parking_site_id': 1,
    'type': 'WOMEN',
    'capacity': 10,
    'realtime_capacity': 9,
    'realtime_free_capacity': 5,
}

parking_site_restriction_component = Schema(
    'ParkingSiteRestriction',
    parking_site_restriction_schema,
    parking_site_restriction_example,
)
